In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('Data.csv')
dataset
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:,-1].values

In [3]:
dataset.isna().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.25, random_state=0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

## Logistic Regression

In [6]:
from sklearn.linear_model import LogisticRegression
cls_LR=LogisticRegression(random_state=0)
cls_LR.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predLR=cls_LR.predict(x_test)
cm=confusion_matrix(y_test, y_predLR)
print(cm)
accuracy_score(y_test, y_predLR)

[[103   4]
 [  5  59]]


0.9473684210526315

## K-Nearest_Neighbors(KNN)

In [8]:
from sklearn.neighbors import KNeighborsClassifier
cls_KNN = KNeighborsClassifier(n_neighbors=5, metric='minkowski',p =2)
cls_KNN.fit(x_train, y_train)

KNeighborsClassifier()

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predKNN=cls_KNN.predict(x_test)
cm=confusion_matrix(y_test, y_predKNN)
print(cm)
accuracy_score(y_test, y_predKNN)

[[103   4]
 [  5  59]]


0.9473684210526315

## Support_Vector_Machine(SVM)-Kernel:Linear

In [10]:
from sklearn.svm import SVC
cls_SVMl=SVC(kernel='linear', random_state=0)
cls_SVMl.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predSVMl=cls_SVMl.predict(x_test)
cm=confusion_matrix(y_test, y_predSVMl)
print(cm)
accuracy_score(y_test, y_predSVMl)

[[102   5]
 [  5  59]]


0.9415204678362573

## Support_Vector_Machine(SVM) -Kernel:rbf

In [12]:
from sklearn.svm import SVC
cls_SVMr=SVC(kernel='rbf', random_state=0)
cls_SVMr.fit(x_train, y_train)

SVC(random_state=0)

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predSVMr=cls_SVMr.predict(x_test)
cm=confusion_matrix(y_test, y_predSVMr)
print(cm)
accuracy_score(y_test, y_predSVMr)

[[102   5]
 [  3  61]]


0.9532163742690059

## Naives_Bayes

In [14]:
from sklearn.naive_bayes import GaussianNB
cls_NB=GaussianNB()
cls_NB.fit(x_train,y_train)

GaussianNB()

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predNB=cls_NB.predict(x_test)
cm=confusion_matrix(y_test, y_predNB)
print(cm)
accuracy_score(y_test, y_predNB)

[[99  8]
 [ 2 62]]


0.9415204678362573

## Decision_Tree_Classification

In [16]:
from sklearn.tree import DecisionTreeClassifier
cls_DT = DecisionTreeClassifier(criterion='entropy', random_state=0)
cls_DT.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predDT=cls_DT.predict(x_test)
cm=confusion_matrix(y_test, y_predDT)
print(cm)
accuracy_score(y_test, y_predDT)

[[103   4]
 [  3  61]]


0.9590643274853801

## Random_Forest_Classification

In [18]:
from sklearn.ensemble import RandomForestClassifier
cls_RF = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
cls_RF.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predRF=cls_RF.predict(x_test)
cm=confusion_matrix(y_test, y_predRF)
print(cm)
accuracy_score(y_test, y_predRF)

[[102   5]
 [  6  58]]


0.935672514619883

In [20]:
## Accuracy score

In [21]:
print('Accuracy score for Logistic Regression:', accuracy_score(y_test, y_predLR))
print('Accuracy score for KNN:', accuracy_score(y_test, y_predKNN))
print('Accuracy score for SVM (kernel: linear):', accuracy_score(y_test, y_predSVMl))
print('Accuracy score for SVM (kernel: rbf):', accuracy_score(y_test, y_predSVMr))
print('Accuracy score for Naives Bayes:', accuracy_score(y_test, y_predNB))
print('Accuracy score for Decision Tree Classification:', accuracy_score(y_test, y_predDT))
print('Accuracy score for Random Forest Classification:', accuracy_score(y_test, y_predRF))

Accuracy score for Logistic Regression: 0.9473684210526315
Accuracy score for KNN: 0.9473684210526315
Accuracy score for SVM (kernel: linear): 0.9415204678362573
Accuracy score for SVM (kernel: rbf): 0.9532163742690059
Accuracy score for Naives Bayes: 0.9415204678362573
Accuracy score for Decision Tree Classification: 0.9590643274853801
Accuracy score for Random Forest Classification: 0.935672514619883
