## Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Import dataset

In [2]:
dataset=pd.read_csv('Data.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
print(y)
print()
print(x)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [3]:
#change y in 1D to 2D
y=y.reshape(len(y), 1)
y

array([[463.26],
       [444.37],
       [488.56],
       ...,
       [429.57],
       [435.74],
       [453.28]])

## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=0)

## Feature scaling (For SVR)

In [5]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_y=StandardScaler()
x_sc_train=sc_x.fit_transform(x)
y_sc_train=sc_y.fit_transform(y)

## Training Multiple Linear Regression model on Training set

In [6]:
from sklearn.linear_model import LinearRegression
reg_MLR=LinearRegression()
reg_MLR.fit(x_train, y_train)

LinearRegression()

## Training Polynomial Regression model on Training set

In [7]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg=PolynomialFeatures(degree=4)
x_poly=poly_reg.fit_transform(x_train)
reg_PR=LinearRegression()
reg_PR.fit(x_poly, y_train)

LinearRegression()

## Training Decision Tree Regression model on Training set

In [8]:
from sklearn.tree import DecisionTreeRegressor
reg_DTR=DecisionTreeRegressor(random_state=0)
reg_DTR.fit(x_train, y_train)

DecisionTreeRegressor(random_state=0)

## Training Random Forest Regression model on Training set

In [9]:
from sklearn.ensemble import RandomForestRegressor
reg_RFR=RandomForestRegressor(n_estimators=10, random_state=0)
reg_RFR.fit(x_train, y_train)

<ipython-input-9-6de0bbf7b745>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  reg_RFR.fit(x_train, y_train)


RandomForestRegressor(n_estimators=10, random_state=0)

## Training Support Vector Regression model on Training set

In [10]:
from sklearn.svm import SVR
reg_SVR=SVR(kernel='rbf')
reg_SVR.fit(x_sc_train, y_sc_train)

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

## Predicting the Test set results MLR

In [11]:

y_pred_MLR=reg_MLR.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_MLR.reshape(len(y_pred_MLR),1), y_test.reshape(len(y_test),1)),1))


[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


## Predicting the Test set results PR

In [12]:

y_pred_PR=reg_PR.predict(poly_reg.transform(x_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_PR.reshape(len(y_pred_PR),1), y_test.reshape(len(y_test),1)),1))


[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.67 463.28]]


## Predicting the Test set results DTR

In [13]:
y_pred_DTR=reg_DTR.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_DTR.reshape(len(y_pred_DTR),1), y_test.reshape(len(y_test),1)),1))


[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.74 463.28]]


## Predicting the Test set results RFR

In [14]:
y_pred_RFR=reg_RFR.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_RFR.reshape(len(y_pred_RFR),1), y_test.reshape(len(y_test),1)),1))


[[434.05 431.23]
 [458.79 460.01]
 [463.02 461.14]
 ...
 [469.48 473.26]
 [439.57 438.  ]
 [460.38 463.28]]


## Predicting the Test set results SVR

In [15]:
y_pred_SVR=sc_y.inverse_transform(reg_SVR.predict(sc_x.transform(x_test)))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_SVR.reshape(len(y_pred_SVR),1), y_test.reshape(len(y_test),1)),1))

[[433.79 431.23]
 [458.09 460.01]
 [460.49 461.14]
 ...
 [470.76 473.26]
 [439.34 438.  ]
 [461.   463.28]]


## Evaluating the Model Performance

In [16]:
from sklearn.metrics import r2_score
print('R2 score for Multiple Linear Regression (MLR):', r2_score(y_test, y_pred_MLR))
print('R2 score for Polynomial Regression (PR):', r2_score(y_test, y_pred_PR))
print('R2 score for Decision Tree Regression (DTR):', r2_score(y_test, y_pred_DTR))
print('R2 score for Random Forest Regression (RFR):', r2_score(y_test, y_pred_RFR))
print('R2 score for Support Vector Regression (SVR):', r2_score(y_test, y_pred_SVR))

R2 score for Multiple Linear Regression (MLR): 0.9325315554761303
R2 score for Polynomial Regression (PR): 0.9458193570471392
R2 score for Decision Tree Regression (DTR): 0.922905874177941
R2 score for Random Forest Regression (RFR): 0.9615908334363876
R2 score for Support Vector Regression (SVR): 0.9499593513690054
